#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.msh # make sure salome 9.5.0 is in you PATH.

./Allrun.pre

runApplication decomposePar

runParallel `getApplication`

runApplication reconstructPar
